from __future__ import annotations
from dataclasses import dataclass
from typing import Sequence
import numpy as np
from .atom import Atom

@dataclass
class Molecule:
    atoms: List[Atom]

    @classmethod
    def from_string(cls, xyz_string: str) -> Molecule:
        lines = xyz_string.strip().splitlines()
        atoms = []
        for line in lines[2:]:
            atom = Atom.from_string(line)
            atoms.append(atom)
        return cls(atoms)   

    def __str__(self): 
        return "\n".join([str(atom) for atom in self.atoms]) 
    
    @property
    def n_electrons(self):
        return sum([atom.n_electrons for atom in self.atoms])
    
    def to_string(self) -> str:
        lines = [str(len(self.atoms)), "Generated by Molecule Class"]
        for atom in self.atoms:
            line = f"{atom.symbol} {atom.coord[0]:.6f} {atom.coord[1]:.6f} {atom.coord[2]:.6f}"
            lines.append(line)
        return "\n".join(lines)