from __future__ import annotations

from dataclasses import dataclass

from .atom import Atom


@dataclass
class Molecule:
    atoms: list[Atom]

    def __str__(self) -> str:
        return "\n".join(str(atom) for atom in self.atoms)

    @property
    def n_electrons(self) -> int:
        return sum(atom.n_electrons for atom in self.atoms)

    @classmethod
    def from_string(cls, xyz_string: str) -> Molecule:
        lines = xyz_string.strip().splitlines()
        atoms: list[Atom] = []
        for line in lines[2:]:
            atoms.append(Atom.from_string(line))
        return cls(atoms)

    def to_string(self) -> str:
        lines = [str(len(self.atoms)), "Generated by Molecule class"]
        for atom in self.atoms:
            lines.append(
                f"{atom.symbol} {atom.coord[0]:.6f} {atom.coord[1]:.6f} {atom.coord[2]:.6f}"
            )
        return "\n".join(lines)
