title: Master Programming 2026
author: Roland Mitric

execute:
  execute_notebooks: "cache"
  timeout: 300

html:
  use_thebe: true
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true

launch_buttons:
  thebe: true
  binderhub_url: https://mybinder.org
  notebook_interface: jupyterlab

repository:
  url: https://github.com/rolandmitric/master_programming_2026
  branch: main
  path_to_book: "book"

thebe:
  binder:
    repo_url: https://github.com/rolandmitric/master_programming_2026
    ref: main
  kernel_name: python3

sphinx:
  config:
    exclude_patterns:
      - _build
      - _build/**
      - develop.ipynb
      - symbolic_eri_generator.ipynb
      - symbolic_kinetic_generator.ipynb
      - symbolic_nuclear_generator.ipynb
      - symbolic_nuclear_permutation_class.ipynb
    html_css_files:
      - custom.css
    html_theme_options:
      collapse_navbar: false
      show_navbar_depth: 2
      max_navbar_depth: 4
